language: es

pipeline:
  - name: HFTransformersNLP
    model_weights: bert-base-multilingual-cased
    model_name: bert
    cache_dir: null
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer
  - name: RegexFeaturizer
  - name: DIETClassifier
    constrain_similarities: true
    random_seed: 42
    use_masked_language_model: true
    epochs: 100
    number_of_transformer_layers: 4
    transformer_size: 256
    drop_rate: 0.2
    weight_sparsity: 0.7
    batch_size:
    - 64
    - 256
    embedding_dimension: 30
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
    model_confidence: linear_norm

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.5
    core_threshold: 0.5
    fallback_action_name: action_default_fallback